### ISSUE TITLE
Usersnap Feedback - Future UI/UX request: be able to drag-reorder Project cards.

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#357] opened 2016-06-24 15:30 UTC
**Sender**: erich.huang@duke.edu
**Comment**: Future UI/UX request: be able to drag-reorder Project cards.
[Open #73 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/73)

![Usersnap Feedback - Future UI/UX request: be able to drag-reorder Project cards.](https://usersnappublic.s3.amazonaws.com/2016-06-24/17-29/7dab25f3-6a57-400a-8a5a-46fd4617847e.png)

**Browser**: Safari 10 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/#/](https://dataservice.duke.edu/#/)
**Screen size**: 1280 x 800 **Browser size**: 1271 x 689

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment] 2016-06-24 15:31
Duplicate of #345 ?

**Comment by erichhuang** [comment] 2016-06-24 15:33
Yes. I can’t remember my own issues.

E

**Comment by caseychoiniere** [comment] 2016-06-24 15:38
Ha! This is a good feature to have. This is cool http://jrowny.github.io/react-absolute-grid/demo/

**Comment by caseychoiniere** [comment] 2017-08-11 21:32
@mgardnerpsu Would it be feasible to add a new property to the project object like `pinned` or ?? so that a user could pin projects? Then the client could use this property to help users sort and keep pinned projects at the top of the list. That way if the user logs on using a different machine or clears their browser cache they would still have the appropriate projects at the top of the list. This might be an easy happy medium that would give nice functionality. I'm picturing something like the Google Inbox app
![screen shot 2017-08-11 at 2 31 19 pm](https://user-images.githubusercontent.com/10411174/29232705-cbb0f598-7ea1-11e7-9977-8cfee458cbf6.png)

**Comment by mgardnerpsu** [comment] 2017-08-23 18:06
Like this idea  - We need a user preferences resource/endpoint - @Donmurry would you mind adding this to our JIRA feature backlog

**Closed as completed** 2022-10-27 15:05 UTC
Labels: enhancement, Feature request
